[project]
name = "openclassroom-data-analysis"
version = "0.1.0"
description = "TP sur l'ACP rÃ©aliser lors d'un cours Openclassrooms"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas>=3.0.0",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
]
